### ISSUE TITLE
REC : skel : metis_det_lingain

### ISSUE THREAD

**Issue by astronomyk** [AstarVienna/METIS_Pipeline#15]
## Description                    

This SKELETON recipe should run with PyEsorex or EDPS and pass the input and output files as set out in the DRL-D.
Additionally the recipe should correctly address the FITS header keywords.
NO functional code is required for this issue to be closed.
                          
## Tasks

- [x] recipe exists and is loadable by EDPS or PyEsorex
- [x] contains empty `run` function
- [x] accepts a SOF file
- [x] saves to disk output files in correct format (i.e. FITS Pri + N-Ext)
- [x] checks input files for required keywords
- [x] adds keywords to output that are required by other recipes
- [ ] unit tests check that input and output are consistent with DRLD
- [ ] unit tests check that header contents are consistent with DRLD

**Comment by astronomyk** [comment]
2024-12-20 :
- Needs to add functionality to check whether input is for IMG or IFU detectors
