### ISSUE TITLE
REC : skel : metis_ifu_reduce

### ISSUE THREAD

**Issue by astronomyk** [AstarVienna/METIS_Pipeline#19]
## Description                    

This SKELETON recipe should run with PyEsorex or EDPS and pass the input and output files as set out in the DRL-D.
Additionally the recipe should correctly address the FITS header keywords.
NO functional code is required for this issue to be closed.
                          
## Tasks

- [x] recipe exists and is loadable by EDPS or PyEsorex
- [x] contains empty `run` function
- [x] accepts a SOF file
- [ ] saves to disk output files in correct format (i.e. FITS Pri + N-Ext)
- [x] checks input files for required keywords
- [ ] adds keywords to output that are required by other recipes
- [x] unit tests check that input and output are consistent with DRLD
- [x] unit tests check that header contents are consistent with DRLD
