### ISSUE TITLE
REC : skel : metis_ifu_rsrf

### ISSUE THREAD

**Issue by astronomyk** [AstarVienna/METIS_Pipeline#20]
## Description                    

This SKELETON recipe should run with PyEsorex or EDPS and pass the input and output files as set out in the DRL-D.
Additionally the recipe should correctly address the FITS header keywords.
NO functional code is required for this issue to be closed.
                          
## Tasks

- [x] recipe exists and is loadable by EDPS or PyEsorex
- [x] contains empty `run` function
- [x] accepts a SOF file
- [x] saves to disk output files in correct format (i.e. FITS Pri + N-Ext)
- [ ] checks input files for required keywords
- [ ] adds keywords to output that are required by other recipes
- [ ] unit tests check that input and output are consistent with DRLD
- [ ] unit tests check that header contents are consistent with DRLD     
- [x] contains instances of all Input / InputSet classes
- [x] contains instances of all Products classes
- [ ] contains docstrings (incl parameter description AND use case example code)
- [ ] updated DRLD to reflect reality of the pipeline code

**Comment by janusbrink** [comment]
Basic skeleton in place - thanks Martin! Added recipe to top-level pipeline (metis_recipes.py) and successfully tested with pyesorex and dummy test data input files.
