### ISSUE TITLE
REC : skel : metis_ifu_wavecal

### ISSUE THREAD

**Issue by astronomyk** [AstarVienna/METIS_Pipeline#22]
## Description                    

This SKELETON recipe should run with PyEsorex or EDPS and pass the input and output files as set out in the DRL-D.
Additionally the recipe should correctly address the FITS header keywords.
NO functional code is required for this issue to be closed.
                          
## Tasks

- [ ] recipe exists and is loadable by EDPS or PyEsorex
- [ ] contains empty `process_image` function
- [ ] accepts a SOF file
- [ ] saves to disk output files in correct format (i.e. FITS Pri + N-Ext)
- [ ] checks input files for required keywords
- [ ] adds keywords to output that are required by other recipes
- [ ] unit tests check that input and output are consistent with DRLD
- [ ] unit tests check that header contents are consistent with DRLD          
- [ ] contains instances of all Input / InputSet classes
- [ ] contains instances of all Products classes
- [ ] contains docstrings (incl parameter description AND use case example code)
- [ ] updated DRLD to reflect reality of the pipeline code
