### ISSUE TITLE
REC : skel : metis_cal_chophome

### ISSUE THREAD

**Issue by astronomyk** [AstarVienna/METIS_Pipeline#23]
## Description                    

This SKELETON recipe should run with PyEsorex or EDPS and pass the input and output files as set out in the DRL-D.
Additionally the recipe should correctly address the FITS header keywords.
NO functional code is required for this issue to be closed.

See pull request [https://github.com/AstarVienna/METIS_Pipeline/pull/78](https://github.com/AstarVienna/METIS_Pipeline/pull/78)
                          
## Tasks

- [x] recipe exists and is loadable by EDPS or PyEsorex
- [x] contains empty `run` function
- [x] accepts a SOF file
- [x] saves to disk output files in correct format (i.e. FITS Pri + N-Ext)
- [x] checks input files for required keywords
- [x] adds keywords to output that are required by other recipes
- [ ] unit tests check that input and output are consistent with DRLD
- [ ] unit tests check that header contents are consistent with DRLD 
- [x] contains instances of all Input / InputSet classes
- [x] contains instances of all Products classes
- [x] contains docstrings (incl parameter description AND use case example code)
- [x] updated DRLD to reflect reality of the pipeline code

**Comment by oczoske** [comment]
I think this is done to the extent required by a skeleton. I don't know how to compare to the DRLD other than by inspection.

**Comment by hugobuddel** [comment]
> I don't know how to compare to the DRLD other than by inspection.

There is no explicit functionality for that in the pipeline (yet). I plan to setup some end-to-end test, that simulates data, processes it, and puts it in the archive. That should help.

**Comment by hugobuddel** [comment]
> I think this is done to the extent required by a skeleton.

I would say things are done once the PR's are actually merged.
