### ISSUE TITLE
REC : skel : metis_lm_img_basic_reduce

### ISSUE THREAD

**Issue by astronomyk** [AstarVienna/METIS_Pipeline#24]
## Description                    

This SKELETON recipe should run with PyEsorex or EDPS and pass the input and output files as set out in the DRL-D.
Additionally the recipe should correctly address the FITS header keywords.
NO functional code is required for this issue to be closed.
                          
## Tasks

All points should be checked against the contents of the DRLD

- [x] recipe exists and is loadable by EDPS or PyEsorex
- [x] contains empty `run` function
- [x] Contains instances of all Input / InputSet 
- [x] Contains instances of all Products
- [x] accepts a SOF file
- [x] saves to disk output files in correct format (i.e. FITS Pri + N-Ext)
- [x] checks input files for required keywords
- [x] adds keywords to output that are required by other recipes
- [ ] unit tests check that input and output are consistent with DRLD
- [ ] unit tests check that header contents are consistent with DRLD 
- [ ] Contains docstrings (incl parameter description AND use example)
- [ ] Updated DRLD to reflect reality in the pipeline code
