### ISSUE TITLE
REC : func : metis_det_dark

### ISSUE THREAD

**Issue by astronomyk** [AstarVienna/METIS_Pipeline#26]
## Description                    

This FUNCTIONAL recipe should work as part of an EDPS workflow.
It should have enough functional code to aid the AIT tests, but DOES NOT need well tested functional code.
Be careful NOT to fall down a rabbit whole here.
                          
## Tasks

- [ ] Add relevant entries to METIS_Simulations to generate set of useful FITS files
- [ ] includes code that provides most basic useful functionality expected from the recipe
- [ ] adds QC parameters related to the AIT functional tests
- [ ] sub-levels of AIT-functionality can be defined here, (abcd...) as some larger recipes may need to provide different functionality at different times
- [ ] recipe runs without crashing as a stand-alone recipe with PyEsorex
- [ ] recipe runs without crashing as part of an EDPS workflow
- [ ] doc-strings contain parameter lists and example code
- [ ] unit tests make use of simulated data for testing basic functionality
- [ ] unit tests for expected edge cases for each recipe method AND util function
- [ ] integration tests simulate all expected (functional) use cases during AIT (See AIT test plans)
- [ ] there is an integration test for EDPS which calls the recipe
